import { GET_CEMENT_CO2 } from "./single-queries/GET-CEMENT-CO2";
import { GET_CEMENT_CO2_PER_CAPITA } from "./single-queries/GET-CEMENT-CO2-PER-CAPITA";
import { GET_CO2 } from "./single-queries/GET-CO2";
import { GET_CO2_PER_CAPITA } from "./single-queries/GET-CO2-PER-CAPITA";
import { GET_CO2_PER_UNIT_ENERGY } from "./single-queries/GET-CO2-PER-UNIT-ENERGY";
import { GET_COAL_CO2 } from "./single-queries/GET-COAL-CO2";
import { GET_COAL_CO2_PER_CAPITA } from "./single-queries/GET-COAL-CO2-PER-CAPITA";
import { GET_CUMULATIVE_CEMENT_CO2 } from "./single-queries/GET-CUMULATIVE-CEMENT-CO2";
import { GET_CUMULATIVE_CO2 } from "./single-queries/GET-CUMULATIVE-CO2";
import { GET_CUMULATIVE_COAL_CO2 } from "./single-queries/GET-CUMULATIVE-COAL-CO2";
import { GET_CUMULATIVE_GAS_CO2 } from "./single-queries/GET-CUMULATIVE-GAS-CO2";
import { GET_CUMULATIVE_OIL_CO2 } from "./single-queries/GET-CUMULATIVE-OIL-CO2";
import { GET_CUMULATIVE_OTHER_CO2 } from "./single-queries/GET-CUMULATIVE-OTHER-CO2";
import { GET_ENERGY_PER_CAPITA } from "./single-queries/GET-ENERGY-PER-CAPITA";
import { GET_GAS_CO2 } from "./single-queries/GET-GAS-CO2";
import { GET_GAS_CO2_PER_CAPITA } from "./single-queries/GET-GAS-CO2-PER-CAPITA";
import { GET_OIL_CO2 } from "./single-queries/GET-OIL-CO2";
import { GET_OIL_CO2_PER_CAPITA } from "./single-queries/GET-OIL-CO2-PER-CAPITA";
import { GET_OTHER_CO2_PER_CAPITA } from "./single-queries/GET-OTHER-CO2-PER-CAPITA";
import { GET_OTHER_INDUSTRY_CO2 } from "./single-queries/GET-OTHER-INDUSTRY-CO2";
import { GET_POPULATION } from "./single-queries/GET-POPULATION";
import { GET_PRIMARY_ENERGY_CONSUMPTION } from "./single-queries/GET-PRIMARY-ENERGY-CONSUMPTION";
import { GET_SHARE_GLOBAL_CEMENT_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CEMENT-CO2";
import { GET_SHARE_GLOBAL_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CO2";
import { GET_SHARE_GLOBAL_COAL_CO2 } from "./single-queries/GET-SHARE-GLOBAL-COAL-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_CEMENT_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-CEMENT-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_COAL_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-COAL-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_GAS_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-GAS-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_OIL_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-OIL-CO2";
import { GET_SHARE_GLOBAL_CUMULATIVE_OTHER_CO2 } from "./single-queries/GET-SHARE-GLOBAL-CUMULATIVE-OTHER-CO2";
import { GET_SHARE_GLOBAL_GAS_CO2 } from "./single-queries/GET-SHARE-GLOBAL-GAS-CO2";
import { GET_SHARE_GLOBAL_OIL_CO2 } from "./single-queries/GET-SHARE-GLOBAL-OIL-CO2";
import { GET_SHARE_GLOBAL_OTHER_CO2 } from "./single-queries/GET-SHARE-GLOBAL-OTHER-CO2";
import { GET_YEARS } from "./single-queries/GET-YEARS";



export default {
  GET_CEMENT_CO2,
  GET_CEMENT_CO2_PER_CAPITA,
  GET_CO2,
  GET_CO2_PER_CAPITA,
  GET_CO2_PER_UNIT_ENERGY,
  GET_COAL_CO2,
  GET_COAL_CO2_PER_CAPITA,
  GET_CUMULATIVE_CEMENT_CO2,
  GET_CUMULATIVE_CO2,
  GET_CUMULATIVE_COAL_CO2,
  GET_CUMULATIVE_GAS_CO2,
  GET_CUMULATIVE_OIL_CO2,
  GET_CUMULATIVE_OTHER_CO2,
  GET_ENERGY_PER_CAPITA,
  GET_GAS_CO2,
  GET_GAS_CO2_PER_CAPITA,
  GET_OIL_CO2,
  GET_OIL_CO2_PER_CAPITA,
  GET_OTHER_CO2_PER_CAPITA,
  GET_OTHER_INDUSTRY_CO2,
  GET_POPULATION,
  GET_PRIMARY_ENERGY_CONSUMPTION,
  GET_SHARE_GLOBAL_CEMENT_CO2,
  GET_SHARE_GLOBAL_CO2,
  GET_SHARE_GLOBAL_COAL_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_CEMENT_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_COAL_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_GAS_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_OIL_CO2,
  GET_SHARE_GLOBAL_CUMULATIVE_OTHER_CO2,
  GET_SHARE_GLOBAL_GAS_CO2,
  GET_SHARE_GLOBAL_OIL_CO2,
  GET_SHARE_GLOBAL_OTHER_CO2,
  GET_YEARS
}